imports:
    - { resource: "services/forms.yml" }
    - { resource: "services/installer.yml" }

services:

  ### Registries
  process_manager.registry.processes:
    class: CoreShop\Component\Registry\ServiceRegistry
    arguments:
      - ProcessManagerBundle\Process\ProcessInterface
      - 'Process Manager Processes'

  process_manager.form.registry.processes:
    class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  ### Processes
  process_manager.process.cli:
    class: ProcessManagerBundle\Process\Cli
    tags:
      - { name: process_manager.process, type: cli, form-type: ProcessManagerBundle\Form\Type\Processes\CliType }

  process_manager.process.pimcore:
    class: ProcessManagerBundle\Process\Pimcore
    tags:
      - { name: process_manager.process, type: pimcore, form-type: ProcessManagerBundle\Form\Type\Processes\PimcoreType }

  ### Event listeners
  ProcessManagerBundle\EventListener\CronListener:
    tags:
      - { name: kernel.event_listener, event: pimcore.system.maintenance, method: run, arguments: }
    arguments:
      - '@process_manager.registry.processes'

  process_manager.process.report:
    class: ProcessManagerBundle\Service\ProcessReport
    arguments:
      - '@process_manager.process.log'

  process_manager.process.log:
    class: ProcessManagerBundle\Service\ProcessLog

  ProcessManagerBundle\Controller\ProcessReportController:
    arguments:
      - '@process_manager.process.report'
    public: true
    tags: ['controller.service_arguments']
